### ISSUE TITLE
add sort and dynamic query functionality

### ISSUE THREAD

**Issue by streamnsight** [frenchbread/meteor-elastic-rest#4]
@frenchbread 

there is no sort capability and the client is only able todo simple static queries.

I implemented sort and from for sortign and pagination, as well as query as a parameter in this PR:

https://github.com/frenchbread/meteor-elastic-rest/pull/3

**Comment by frenchbread** [comment]
@streamnsight Thanks for your contribution!

PR #3 is merged now. Closing this issue.
